/** Author-first UX acceptance against the real local BFF. No interception or model calls. */
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from 'playwright';
import { shelfOf, openBook, openChapterCreateForm } from './business-journey.mjs';

const origin = 'http://127.0.0.1:8787';
const api = `${origin}/api/v1`;
const run = `author-ui-${Date.now()}`;
const directory = resolve('data/acceptance', run);
await mkdir(directory, { recursive: true, mode: 0o700 });
const osKeys = ['PATH', 'HOME', 'USER', 'LOGNAME', 'TMPDIR', 'TEMP', 'TMP', 'LANG', 'LC_ALL', 'TZ', 'SYSTEMROOT', 'WINDIR'];
const env = Object.fromEntries(osKeys.flatMap(key => process.env[key] === undefined ? [] : [[key, process.env[key]]]));
const browser = await chromium.launch({ headless: true, env });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: 'zh-CN' });
const page = await context.newPage();
page.setDefaultTimeout(15000);
const errors = [];
page.on('pageerror', () => errors.push('Uncaught application error'));
const result = { run, origin, passed: false, modelRequestsSent: 0, checks: [], screenshots: [], workId: null };
page.on('request', request => {
  if (request.method() === 'POST' && /\/sessions\/[^/]+\/messages$/.test(new URL(request.url()).pathname)) result.modelRequestsSent++;
});
const shots = async (name) => {
  const path = resolve(directory, `${name}.png`);
  await page.screenshot({ path, fullPage: true, animations: 'disabled' });
  result.screenshots.push(path);
};
const noOverflow = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No page-level horizontal overflow');
try {
  const config = await (await context.request.get(`${api}/auth/config`)).json();
  assert.equal(config.mode, 'development');
  await page.goto(origin);
  await page.getByRole('button', { name: '作者 author', exact: true }).click();
  await shelfOf(page).waitFor();
  const title = `雾港来信 · ${run}`;
  await page.getByRole('button', { name: '新建书本', exact: true }).click();
  await page.getByLabel('书名', { exact: true }).fill(title);
  await page.getByLabel('简介').fill('一座灯塔，一封迟了二十年的信。界面验收作品，保留供检查。');
  const created = page.waitForResponse(r => r.url() === `${api}/works` && r.request().method() === 'POST');
  await page.getByRole('button', { name: '创建并开始写作', exact: true }).click();
  const response = await created;
  assert.equal(response.status(), 201);
  result.workId = (await response.json()).id;
  const chapterInput = await openChapterCreateForm(page);
  const chapterTitle = '第一章　雾中的灯塔';
  await chapterInput.fill(chapterTitle);
  const chapterCreated = page.waitForResponse(r => r.url() === `${api}/works/${result.workId}/chapters` && r.request().method() === 'POST');
  await page.getByRole('button', { name: '新建章节', exact: true }).click();
  const chapter = await (await chapterCreated).json();
  const source = '# 潮声之前\n\n雾从海面升起的时候，林遥正在擦拭灯塔的玻璃。\n她看见远处有一点微弱的光，忽明忽暗，像是谁在给海岸写一封信。\n\n“今天不会有船来。”老周说。\n\n她没有回答。掌心那封**迟了二十年的信**，还带着海水的温度。\n\n## 写作备忘\n\n- 林遥：守塔人的女儿，相信父亲仍然活着。\n- 老周：唯一知道沉船真相的人。\n\n> 灯亮着的时候，迷路的人总会回来。\n\n| 线索 | 本章伏笔 |\n| --- | --- |\n| 蓝色信封 | 邮戳停在二十年前 |\n| 灯塔暗号 | 三长两短，来自失踪的船 |\n\n![海港示意](https://example.invalid/no-image-request.png)\n\n  尾声保留两格  \n\n';
  let imageRequests = 0;
  page.on('request', request => { if (request.url().includes('no-image-request')) imageRequests++; });
  const editor = page.getByLabel(`章节正文：${chapterTitle}`, { exact: true }).locator('[contenteditable="true"]');
  await editor.fill(source);
  await page.getByLabel('当前修改目标', { exact: true }).filter({ hasText: chapterTitle }).waitFor();
  await page.getByText('当前有未保存修改。助手只读取已保存版本；如需修改这份草稿，请先保存。', { exact: true }).waitFor();
  const saveUrl = `${api}/works/${result.workId}/chapters/${chapter.id}`;
  const saved = page.waitForResponse(r => r.url() === saveUrl && r.request().method() === 'PUT');
  await page.keyboard.press('Control+s');
  assert.equal((await saved).status(), 200);
  assert.equal((await (await context.request.get(saveUrl)).json()).text, source);
  await page.getByRole('button', { name: '阅读', exact: true }).click();
  await page.getByRole('heading', { name: '潮声之前', exact: true }).waitFor();
  assert.equal(await page.locator('.manuscript-reading table').count(), 1);
  assert.equal(await page.locator('.manuscript-reading img').count(), 0);
  assert.equal(imageRequests, 0);
  await noOverflow();
  await shots('desktop-reading');
  result.checks.push('Ctrl+S saves exact whitespace/newlines through real BFF; selected chapter chip and dirty warning; semantic headings/lists/table; no image request');

  await page.getByRole('button', { name: '专注写作', exact: true }).click();
  assert.equal(await page.getByRole('navigation', { name: '书内目录', exact: true }).isVisible(), false);
  assert.equal(await page.locator('.assistant').count(), 1, 'Focus preserves mounted assistant');
  await noOverflow();
  await shots('desktop-focus');
  await page.getByRole('button', { name: '退出专注', exact: true }).click();
  await page.reload();
  await openBook(page, title);
  await page.getByRole('heading', { name: '潮声之前', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '阅读', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.getByRole('button', { name: '编辑原文', exact: true }).click();
  assert.deepEqual(await editor.locator('p').allTextContents(), source.split('\n'));
  result.checks.push('Reload opens saved chapter in reading mode; explicit edit restores exact source; focus hides without unmounting');

  const dirty = source + '没有发送给助手的本地草稿。';
  await editor.fill(dirty);
  await page.getByRole('button', { name: '阅读', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await noOverflow();
  await shots('mobile-reading');
  const nav = page.getByRole('navigation', { name: '创作区域', exact: true });
  await nav.getByRole('button', { name: '助手', exact: true }).click();
  const composer = page.getByLabel('消息输入', { exact: true });
  await composer.fill('让这一章的悬念再强一点。');
  await noOverflow();
  await shots('mobile-assistant');
  await nav.getByRole('button', { name: '目录', exact: true }).click();
  await shots('mobile-directory');
  await page.getByRole('button', { name: '故事大纲', exact: false }).click();
  assert.equal(await nav.getByRole('button', { name: '正文', exact: true }).getAttribute('aria-pressed'), 'true');
  await nav.getByRole('button', { name: '助手', exact: true }).click();
  assert.equal(await composer.inputValue(), '让这一章的悬念再强一点。');
  await page.getByLabel('当前修改目标', { exact: true }).filter({ hasText: '故事大纲' }).waitFor();
  await nav.getByRole('button', { name: '目录', exact: true }).click();
  await page.getByRole('button').filter({ hasText: chapterTitle }).first().click();
  assert.equal(await nav.getByRole('button', { name: '正文', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.getByRole('button', { name: '编辑原文', exact: true }).click();
  assert.deepEqual(await editor.locator('p').allTextContents(), dirty.split('\n'));
  assert.equal((await (await context.request.get(saveUrl)).json()).text, source, 'Draft never persisted implicitly');
  await noOverflow();
  result.checks.push('390px mobile: panes stay mounted, selection returns to content, unsaved chapter and message drafts preserved, target follows outline/chapter, no implicit save/send, no horizontal overflow');
  assert.deepEqual(errors, []);
  result.passed = true;
} catch (error) {
  result.error = { name: error.name, message: String(error.message).slice(0, 1800) };
  await shots('failure').catch(() => undefined);
  process.exitCode = 1;
} finally {
  await browser.close();
  await writeFile(resolve(directory, 'result.json'), JSON.stringify(result, null, 2) + '\n', { mode: 0o600 });
  console.log(JSON.stringify(result, null, 2));
}
